/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rs.ac.bg.fon.ai.np.NPKlijent.ui.form.pokvarendeo;


import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;

import rs.ac.bg.fon.ai.np.NPCommon.domain.Automobil;
import rs.ac.bg.fon.ai.np.NPCommon.domain.PokvareniDeo;
import rs.ac.bg.fon.ai.np.NPCommon.domain.UoceniKvar;
import rs.ac.bg.fon.ai.np.NPKlijent.logic.Controller;
import rs.ac.bg.fon.ai.np.NPKlijent.ui.components.TableModelPokvarenDeo;
import rs.ac.bg.fon.ai.np.NPKlijent.ui.form.pokvarendeo.FrmPokvarenDeoDetalji;


/**
 *
 * @author Asus
 */
public class FrmIzmeniPokvarenDeo extends javax.swing.JPanel {

    List<PokvareniDeo> listaSvihPokvarenihDelova;

    /**
     * Creates new form FrmIzmeniPokvarenDeo
     */
    public FrmIzmeniPokvarenDeo() {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtTablice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnPrikaziSvePokvareneDelove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPokvareniDelovi = new javax.swing.JTable();
        btnIzmeniPokvarenDeo = new javax.swing.JButton();
        btnObrisiPokvarenDeo = new javax.swing.JButton();
        btnPretrazi = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Pokvareni delovi");

        jLabel2.setText("Filtriraj prema tablicama automobila");

        jLabel3.setText("Pokvareni delovi");

        btnPrikaziSvePokvareneDelove.setText("Prikazi sve pokvarene delove");
        btnPrikaziSvePokvareneDelove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziSvePokvareneDeloveActionPerformed(evt);
            }
        });

        tblPokvareniDelovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPokvareniDelovi);

        btnIzmeniPokvarenDeo.setText("Izmeni");
        btnIzmeniPokvarenDeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniPokvarenDeoActionPerformed(evt);
            }
        });

        btnObrisiPokvarenDeo.setText("Obrisi");
        btnObrisiPokvarenDeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPokvarenDeoActionPerformed(evt);
            }
        });

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrikaziSvePokvareneDelove))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIzmeniPokvarenDeo)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiPokvarenDeo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTablice, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPretrazi)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTablice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(btnPrikaziSvePokvareneDelove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeniPokvarenDeo)
                    .addComponent(btnObrisiPokvarenDeo))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrikaziSvePokvareneDeloveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziSvePokvareneDeloveActionPerformed
        // TODO add your handling code here:
        try {
            PokvareniDeo pd = new PokvareniDeo();
            Automobil a = new Automobil();
            a.setTablice("");
            UoceniKvar uk = new UoceniKvar();
            uk.setAutomobil(a);
            pd.setUoceniKvar(uk);
            listaSvihPokvarenihDelova = Controller.getInstance().pronadjiPokvareneDelove(pd);
            ((TableModelPokvarenDeo) tblPokvareniDelovi.getModel()).setListaPokvarenihDelova(listaSvihPokvarenihDelova);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju svih pokvarenih delova!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPrikaziSvePokvareneDeloveActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        // TODO add your handling code here:
        if (txtTablice.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Unesite tablice!", "Greska pri unosu", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtTablice.getText().contains(" ")) {
            JOptionPane.showMessageDialog(this, "Broj tablica ne sme da sadrzi blanko znak!", "Greska pri unosu", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String tablice = txtTablice.getText().trim();

        try {
            PokvareniDeo pd = new PokvareniDeo();
            Automobil a = new Automobil();
            a.setTablice(tablice);
            UoceniKvar uk = new UoceniKvar();
            uk.setAutomobil(a);
            pd.setUoceniKvar(uk);
            List<PokvareniDeo> pokvareniDeloviPretraga = Controller.getInstance().pronadjiPokvareneDelove(pd);
            ((TableModelPokvarenDeo) tblPokvareniDelovi.getModel()).setListaPokvarenihDelova(pokvareniDeloviPretraga);
           
            if (pokvareniDeloviPretraga == null || pokvareniDeloviPretraga.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje pokvarene delove po zadatoj vrednosti!!", "Potvrda", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, "Sistem je nasao pokvarene delove po zadatoj vredonsti!", "Potvrda", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje pokvarene delove po zadatoj vrednosti!\n" + ex.getMessage(), "Greska pri pretrazi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnObrisiPokvarenDeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPokvarenDeoActionPerformed
        // TODO add your handling code here:
        if (tblPokvareniDelovi.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Niste selektovali pokvaren deo!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        TableModelPokvarenDeo tm = (TableModelPokvarenDeo) tblPokvareniDelovi.getModel();
        PokvareniDeo pokvareniDeoZaBrisanje = tm.getListaPokvarenihDelova().get(tblPokvareniDelovi.getSelectedRow());
        pokvareniDeoZaBrisanje.setUsloviZaUpdate(pokvareniDeoZaBrisanje.getUoceniKvar().getAutomobil().getTablice(), pokvareniDeoZaBrisanje.getUoceniKvar().getKvarID(), pokvareniDeoZaBrisanje.getDeo().getDeoID());

        try {
            Controller.getInstance().obrisiPokvarenDeo(pokvareniDeoZaBrisanje);
            //nije se desila greska
            JOptionPane.showMessageDialog(this, "Sistem je izbrisao pokvaren deo!", "Potvrda", JOptionPane.INFORMATION_MESSAGE);
            tm.izbrisiPokvarenDeo(pokvareniDeoZaBrisanje);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da izbrise pokvaren deo!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiPokvarenDeoActionPerformed

    private void btnIzmeniPokvarenDeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniPokvarenDeoActionPerformed
        // TODO add your handling code here:
        if (tblPokvareniDelovi.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Niste selektovali pokvaren deo!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        TableModelPokvarenDeo tm = (TableModelPokvarenDeo) tblPokvareniDelovi.getModel();
        PokvareniDeo pokvareniDeo = tm.getListaPokvarenihDelova().get(tblPokvareniDelovi.getSelectedRow());
        try {
            JDialog dialog = new JDialog((JDialog) this.getTopLevelAncestor(), "Izmeni pokvaren deo", true);
            JPanel frmPokvarenDeoIzmeni = new FrmPokvarenDeoDetalji(pokvareniDeo, (TableModelPokvarenDeo) tblPokvareniDelovi.getModel());
            dialog.add(frmPokvarenDeoIzmeni);
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialog.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju pokvarenog dela!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniPokvarenDeoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniPokvarenDeo;
    private javax.swing.JButton btnObrisiPokvarenDeo;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikaziSvePokvareneDelove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblPokvareniDelovi;
    private javax.swing.JTextField txtTablice;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        tblPokvareniDelovi.setModel(new TableModelPokvarenDeo());
        //vratiSvePokvareneDelove();
    }
//
//    void refreshTabela() {
//        TableModelPokvarenDeo tm = (TableModelPokvarenDeo) tblPokvareniDelovi.getModel();
//        tm.fireTableDataChanged();
//    }

//    private void vratiSvePokvareneDelove() {
//       
//    }
    public List<PokvareniDeo> getListaSvihPokvarenihDelova() {
        return listaSvihPokvarenihDelova;
    }

    public JTable getTblPokvareniDelovi() {
        return tblPokvareniDelovi;
    }

}
