/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rs.ac.bg.fon.ai.np.NPKlijent.ui.form.pokvarendeo;


import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

import rs.ac.bg.fon.ai.np.NPCommon.domain.Automobil;
import rs.ac.bg.fon.ai.np.NPCommon.domain.DeoAutomobila;
import rs.ac.bg.fon.ai.np.NPCommon.domain.PokvareniDeo;
import rs.ac.bg.fon.ai.np.NPCommon.domain.UoceniKvar;
import rs.ac.bg.fon.ai.np.NPKlijent.logic.Controller;
import rs.ac.bg.fon.ai.np.NPKlijent.ui.components.TableModelPokvarenDeo;


/**
 *
 * @author Asus
 */
public class FrmPokvarenDeoDetalji extends javax.swing.JPanel {

    PokvareniDeo pokvareniDeo;
    TableModelPokvarenDeo tm;
    /**
     * Creates new form FrmPokvarenDeoDetalji
     */
    public FrmPokvarenDeoDetalji() {
        initComponents();
        prepareView();
    }

    public FrmPokvarenDeoDetalji(PokvareniDeo pokvareniDeo, TableModelPokvarenDeo tm) {
        initComponents();
        this.pokvareniDeo = pokvareniDeo;
        this.tm = tm;
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cbDeoAutomobila = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbAutomobili = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbKvaroviZaAutomobil = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtCenaPopravke = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnSacuvaj = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Pokvaren deo");

        jLabel2.setText("Izaberi pokvaren deo automobila");

        cbDeoAutomobila.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Izaberi automobil");

        cbAutomobili.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAutomobili.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAutomobiliItemStateChanged(evt);
            }
        });

        jLabel4.setText("Izaberi kvar za taj automobil");

        cbKvaroviZaAutomobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbKvaroviZaAutomobil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbKvaroviZaAutomobilItemStateChanged(evt);
            }
        });

        jLabel5.setText("Cena popravke");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("€");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNazad))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbDeoAutomobila, 0, 196, Short.MAX_VALUE)
                                    .addComponent(cbAutomobili, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbKvaroviZaAutomobil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCenaPopravke, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel6)))))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbAutomobili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbKvaroviZaAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbDeoAutomobila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCenaPopravke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnNazad))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbKvaroviZaAutomobilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbKvaroviZaAutomobilItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cbKvaroviZaAutomobilItemStateChanged

    private void cbAutomobiliItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAutomobiliItemStateChanged
        // TODO add your handling code here:
        if (cbAutomobili.getSelectedIndex() == -1) {
            return;
        }
        Automobil auto = (Automobil) cbAutomobili.getSelectedItem();
        cbKvaroviZaAutomobil.setModel(new DefaultComboBoxModel(auto.getUoceniKvarovi().toArray()));

    }//GEN-LAST:event_cbAutomobiliItemStateChanged

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        ((JDialog) this.getTopLevelAncestor()).dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        // TODO add your handling code here:
        if (cbAutomobili.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Niste izabrali automobil!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (cbKvaroviZaAutomobil.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Niste izabrali kvar!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (cbDeoAutomobila.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Niste izabrali deo automobila!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtCenaPopravke.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Niste uneli cenu!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!txtCenaPopravke.getText().matches("[+-]?([0-9]*[.])?[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Unesite samo brojeve za cenu!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double cena = Double.parseDouble(txtCenaPopravke.getText());
        if (cena <= 0) {
            JOptionPane.showMessageDialog(this, "Cena mora biti veca od nule!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (pokvareniDeo == null) {
            UoceniKvar k = (UoceniKvar) cbKvaroviZaAutomobil.getSelectedItem();
            DeoAutomobila deo = (DeoAutomobila) cbDeoAutomobila.getSelectedItem();
            PokvareniDeo pokvareniDeo = new PokvareniDeo(k, deo, cena);
            try {
                
                Controller.getInstance().sacuvajPokvareniDeo(pokvareniDeo);
                //nije puklo
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio pokvareni deo!", "Potvrda", JOptionPane.INFORMATION_MESSAGE);
                int opcija = JOptionPane.showConfirmDialog(this, "Nastavi unos?", "Potvrda", JOptionPane.YES_NO_OPTION);
                if (opcija == JOptionPane.YES_OPTION) {
                    pripremiFormuZaNoviUnos();
                } else {
                    ((JDialog) this.getTopLevelAncestor()).dispose();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti pokvaren deo!\n"+ ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            //prvo zapamti stare vrednosti
//            String stareTablice = pokvareniDeo.getUoceniKvar().getAutomobil().getTablice();
//            int stariKvarID = pokvareniDeo.getUoceniKvar().getKvarID();
//            int stariDeoID = pokvareniDeo.getDeo().getDeoID();

            //ipak bi dobrodosla tabela prvo da vidi dal ga nema
            //List<PokvareniDeo> delovi = ((TableModelPokvarenDeo) frm.getTblPokvareniDelovi().getModel()).getListaPokvarenihDelova();
            //ovde ne smem da menjam ovaj nego novi koji cu uporediti sa ovim
            PokvareniDeo deoNovi = new PokvareniDeo((UoceniKvar) cbKvaroviZaAutomobil.getSelectedItem(), (DeoAutomobila) cbDeoAutomobila.getSelectedItem(), cena);
            //ovo u valdiate izvrsi
//            if (delovi.contains(deoNovi)) {
//                JOptionPane.showMessageDialog(this, "Greska!\nVec postoji takav pokvaren deo.", "Greska", JOptionPane.ERROR_MESSAGE);
//                //((JDialog)this.getTopLevelAncestor()).dispose();
//                return;
//            }
            deoNovi.setUsloviZaUpdate(pokvareniDeo.getUoceniKvar().getAutomobil().getTablice(), pokvareniDeo.getUoceniKvar().getKvarID(), pokvareniDeo.getDeo().getDeoID());
//            pokvareniDeo.setUoceniKvar((UoceniKvar) cbKvaroviZaAutomobil.getSelectedItem());
//            pokvareniDeo.setDeo((DeoAutomobila) cbDeoAutomobila.getSelectedItem());
//            pokvareniDeo.setCena(cena);

//            if(frm.getListaSvihPokvarenihDelova().contains(pokvareniDeo)){
//                JOptionPane.showMessageDialog(this, "Greska!\nVec postoji takav pokvaren deo.", "Greska", JOptionPane.ERROR_MESSAGE);
//                return;
//            }else{
//            }
            //ne mora ova provera iznad jer ce baza proveriti dal vec postoji
            try {
                
                Controller.getInstance().izmeniPokvareniDeo(deoNovi);
                JOptionPane.showMessageDialog(this, "Sistem je izmenio pokvareni deo!", "Potvrda", JOptionPane.INFORMATION_MESSAGE);
                //pokvareniDeo = deoNovi;
                tm.izbrisiPokvarenDeo(pokvareniDeo);
                tm.dodajPokvarenDeo(deoNovi);
                ((JDialog)this.getTopLevelAncestor()).dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti pokvaren deo!\n"/* + ex.getMessage()*/, "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<String> cbAutomobili;
    private javax.swing.JComboBox<String> cbDeoAutomobila;
    private javax.swing.JComboBox<String> cbKvaroviZaAutomobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtCenaPopravke;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        ucitajAutomobile();
        ucitajDeloveAutomobila();

        if (pokvareniDeo != null) {
            cbAutomobili.setSelectedItem(pokvareniDeo.getUoceniKvar().getAutomobil());
            cbKvaroviZaAutomobil.setSelectedItem(pokvareniDeo.getUoceniKvar());
            //cbAutomobili.setEnabled(false);
            //cbKvaroviZaAutomobil.setEnabled(false);
            cbDeoAutomobila.setSelectedItem(pokvareniDeo.getDeo());
            //cbDeoAutomobila.setEnabled(false);
            txtCenaPopravke.setText(String.valueOf(pokvareniDeo.getCena()));
        }
    }

    private void ucitajAutomobile() {
        try {
            Automobil auto = new Automobil();
            auto.setImePrezimeVlasnika("");
            List<Automobil> automobili = Controller.getInstance().pronadjiAutomobile(auto);
            cbAutomobili.setModel(new DefaultComboBoxModel(automobili.toArray()));
            cbAutomobili.setSelectedIndex(-1);
            cbKvaroviZaAutomobil.removeAllItems();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greski pri ucitavanju automobila!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void ucitajDeloveAutomobila() {
        try {
            List<DeoAutomobila> deloviAutomobila = Controller.getInstance().ucitajListuDelovaAutomobila();
            cbDeoAutomobila.setModel(new DefaultComboBoxModel(deloviAutomobila.toArray()));
            cbDeoAutomobila.setSelectedIndex(-1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju delova automobila!", "Greska", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void pripremiFormuZaNoviUnos() {
        cbAutomobili.setSelectedIndex(-1);
        cbKvaroviZaAutomobil.setSelectedIndex(-1);
        cbDeoAutomobila.setSelectedIndex(-1);
        txtCenaPopravke.setText("");
    }
}
