/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rs.ac.bg.fon.ai.np.NPKlijent.ui.form.pokvarendeo;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import rs.ac.bg.fon.ai.np.NPCommon.domain.Automobil;
import rs.ac.bg.fon.ai.np.NPKlijent.ui.components.TableModelAutomobil;
import rs.ac.bg.fon.ai.np.NPKlijent.ui.form.automobil.FrmAutoDetalji;
import rs.ac.bg.fon.ai.np.NPKlijent.ui.form.nalog.FrmNalog;

/**
 * Pomocna forma za pretragu automobila prema tablicama.
 * 
 * @author Luka Obrenic
 */
public class FrmPretragaAuto extends javax.swing.JPanel {

    /**
     * Lista svih automobila iz koje ce se vrsiti pretraga, tipa {@link Automobil}.
     */
    List<Automobil> automobili;
    /**
     * Panel koji je pozvao ovu formu, tipa {@link JPanel}.
     */
    JPanel gf;
    /**
     * Kreira novu formu FrmPretragaAuto
     */
    public FrmPretragaAuto(JPanel gf, List<Automobil> automobili) {
        initComponents();
        this.gf = gf;
        this.automobili = automobili;
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTablice = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        btnOdaberi = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        btnDodajAutomobil = new javax.swing.JButton();

        jLabel1.setText("Unesi tablice");

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnOdaberi.setText("Odaberi");
        btnOdaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdaberiActionPerformed(evt);
            }
        });

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        btnDodajAutomobil.setText("Dodaj novi automobil");
        btnDodajAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajAutomobilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodajAutomobil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOdaberi)
                        .addGap(18, 18, 18)
                        .addComponent(btnNazad))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtTablice, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnPretrazi))
                        .addComponent(jSeparator3)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTablice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOdaberi)
                    .addComponent(btnNazad)
                    .addComponent(btnDodajAutomobil))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metoda koja se poziva klikom na dugme "Pretrazi".
     * 
     * Iz liste svih automobila, bira one cija tablica pocinje sa vrednosti koja je 
     * uneta u teksualno polje i dodaje ih u podlistu, koja se prikazuje u tabeli.
     */
    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        // TODO add your handling code here:
        //pretrazi treba samo da nadje te iz liste automobila
        if(txtTablice.getText().isBlank()){
            ((TableModelAutomobil)jTable1.getModel()).setListaAutomobila(this.automobili);
            return;
        }
        
        List<Automobil> pretraga = new ArrayList<>();
        String tablice = txtTablice.getText().toLowerCase().trim();
        for(Automobil auto : this.automobili){
            if(auto.getTablice().toLowerCase().startsWith(tablice)){
                //dodaj ga u listu
                pretraga.add(auto);
            }
        }
        if(pretraga.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ne postoji takav automobil!", "Potvrda", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        ((TableModelAutomobil)jTable1.getModel()).setListaAutomobila(pretraga);
    }//GEN-LAST:event_btnPretraziActionPerformed

    /**
     * Metoda koja se poziva klikom na dugme "Odaberi".
     * 
     * Selektovani automobil iz tabele postavlja kao selektovani u combobox-u forme koja je pozvala ovu formu.
     */
    private void btnOdaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdaberiActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Niste selektovali!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        TableModelAutomobil tm = (TableModelAutomobil)jTable1.getModel();
        Automobil a = tm.getListaAutomobila().get(jTable1.getSelectedRow());
        //sad treba da se odabere u cb
        if(gf instanceof FrmNalog){
            ((FrmNalog)gf).postaviAutomobilCB(a);  
        }
        if(gf instanceof FrmPokvarenDeo){
            ((FrmPokvarenDeo)gf).postaviAutomobilCB(a);  
        }
        ((JDialog)this.getTopLevelAncestor()).dispose();
    }//GEN-LAST:event_btnOdaberiActionPerformed

    /**
     * Gasi formu.
     */
    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        ((JDialog)this.getTopLevelAncestor()).dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnDodajAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajAutomobilActionPerformed
        // TODO add your handling code here:
        try{
            JDialog dialog = new JDialog((JDialog) this.getTopLevelAncestor(), "Kreiraj novog vlasnika", true);
            JPanel frmAutoDetalji = new FrmAutoDetalji(this);
            dialog.add(frmAutoDetalji);
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialog.setVisible(true);
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Greska pri otvaranju forme za dodavanje novog automobil!", "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDodajAutomobilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajAutomobil;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnOdaberi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtTablice;
    // End of variables declaration//GEN-END:variables

    /**
     * Inicijalizuje prikaz tabele.
     */
    private void prepareView() {
        //ovde treba da se odradi init stanje a to je da su svi automobil prikazani
        TableModelAutomobil tm = new TableModelAutomobil();
        jTable1.setModel(tm);
        tm.setListaAutomobila(automobili);
    }

    public void dodajAutoUTabelu(Automobil auto) {
        if(gf instanceof FrmNalog){
            ((FrmNalog)gf).dodajAutoUCB(auto);  
        }
        if(gf instanceof FrmPokvarenDeo){
            ((FrmPokvarenDeo)gf).dodajAutoUCB(auto);  
        }
        ((TableModelAutomobil)jTable1.getModel()).dodajAutomobil(auto);
    }
}
