/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rs.ac.bg.fon.ai.np.NPKlijent.ui.form.pokvarendeo;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ai.np.NPCommon.domain.PokvareniDeo;
import rs.ac.bg.fon.ai.np.NPKlijent.logic.Controller;
import rs.ac.bg.fon.ai.np.NPKlijent.ui.components.TableModelPokvarenDeo;

/**
 *
 * @author Asus
 */
public class FrmPokvarenDeoDetalji extends javax.swing.JPanel {
    
    private PokvareniDeo pokvareniDeo;
    TableModelPokvarenDeo tm;
    
    /**
     * Creates new form FrmPokvarenDeoDetalji
     */
    public FrmPokvarenDeoDetalji(PokvareniDeo pokvareniDeo, TableModelPokvarenDeo tm) {
        initComponents();
        this.pokvareniDeo = pokvareniDeo;
        this.tm = tm;
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAutomobil = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblKvar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDeo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnIzmeniCenu = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();

        jLabel1.setText("Automobil:");

        lblAutomobil.setText("jLabel2");

        jLabel2.setText("Kvar:");

        lblKvar.setText("jLabel2");

        jLabel3.setText("Deo automobila:");

        lblDeo.setText("jLabel2");

        jLabel4.setText("Cena:");

        jLabel5.setText("€");

        btnIzmeniCenu.setText("Izmeni cenu");
        btnIzmeniCenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniCenuActionPerformed(evt);
            }
        });

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAutomobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeo, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnIzmeniCenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNazad)
                        .addGap(145, 145, 145)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblAutomobil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblKvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDeo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeniCenu)
                    .addComponent(btnNazad))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        ((JDialog) this.getTopLevelAncestor()).dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnIzmeniCenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniCenuActionPerformed
        // TODO add your handling code here:
        if (!txtCena.getText().matches("[+-]?([0-9]*[.])?[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Cena nije validna!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double cena = Double.parseDouble(txtCena.getText());
        if (cena <= 0) {
            JOptionPane.showMessageDialog(this, "Cena mora biti veca od nule!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(cena == this.pokvareniDeo.getCena()){
            ((JDialog) this.getTopLevelAncestor()).dispose();
        }else {
            //ovde treba izmena
            try {
                this.pokvareniDeo.setUsloviZaUpdate(this.pokvareniDeo.getUoceniKvar().getAutomobil().getTablice(), this.pokvareniDeo.getUoceniKvar().getKvarID(), pokvareniDeo.getDeo().getDeoID());
                this.pokvareniDeo.setCena(cena);
                Controller.getInstance().izmeniPokvareniDeo(this.pokvareniDeo);
                JOptionPane.showMessageDialog(this, "Sistem je izmenio pokvareni deo!", "Potvrda", JOptionPane.INFORMATION_MESSAGE);
                ((JDialog)this.getTopLevelAncestor()).dispose();
                tm.refresh();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti pokvaren deo!\n"/* + ex.getMessage()*/, "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnIzmeniCenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniCenu;
    private javax.swing.JButton btnNazad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAutomobil;
    private javax.swing.JLabel lblDeo;
    private javax.swing.JLabel lblKvar;
    private javax.swing.JTextField txtCena;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        lblAutomobil.setText(this.pokvareniDeo.getUoceniKvar().getAutomobil().toString());
        lblKvar.setText(this.pokvareniDeo.getUoceniKvar().getOpis());
        lblDeo.setText(this.pokvareniDeo.getDeo().getNaziv());
        txtCena.setText(this.pokvareniDeo.getCena()+"");
    }
}
