/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rs.ac.bg.fon.ai.np.NPKlijent.ui.form.nalog;

import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ai.np.NPCommon.domain.NalogZaServisiranje;
import rs.ac.bg.fon.ai.np.NPCommon.domain.PokvareniDeo;
import rs.ac.bg.fon.ai.np.NPKlijent.logic.Controller;
import rs.ac.bg.fon.ai.np.NPKlijent.ui.components.TableModelPokvarenDeo;

/**
 * Read-only forma za prikaz detalja o nalogu. 
 * 
 * Prosledjuje joj se nalog, za koji treba prikazati podatke, preko konstruktora.
 * 
 * @author Luka Obrenic
 */
public class FrmNalogDetalji extends javax.swing.JPanel {
    /**
     * Nalog za koji se prikazuju podaci.
     */
    NalogZaServisiranje nalog;

    /**
     * Kreira novu formu FrmNalogDetalji
     */
    public FrmNalogDetalji(NalogZaServisiranje nalog) {
        initComponents();
        this.nalog= nalog;
        prepareView();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lblAutomobil = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblKvar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblServiser = new javax.swing.JLabel();
        lblDatumKreiranja = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDatumZavrsetka = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCena = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPokvareniDelovi = new javax.swing.JTable();
        btnNazad = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("Nalog");

        jLabel2.setText("Automobil:");

        lblAutomobil.setText("lblauto");

        jLabel3.setText("Kvar:");

        lblKvar.setText("lblauto");

        jLabel4.setText("Serviser:");

        lblServiser.setText("lblauto");

        lblDatumKreiranja.setText("lblauto");

        jLabel5.setText("Datum kreiranja:");

        lblStatus.setText("lblauto");

        jLabel6.setText("Status:");

        lblDatumZavrsetka.setText("lblauto");

        jLabel7.setText("Datum izvrsenja:");

        lblCena.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblCena.setText("lblauto");

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setText("Cena:");

        jLabel9.setText("Pokvareni delovi");

        tblPokvareniDelovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPokvareniDelovi);

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(69, 69, 69))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel7)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblServiser, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblDatumKreiranja, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblDatumZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(lblCena, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(136, 136, 136))))
                                            .addGap(99, 99, 99)))
                                    .addComponent(lblKvar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNazad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblAutomobil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKvar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblServiser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblDatumKreiranja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblDatumZavrsetka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblCena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNazad)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Zatvara ovu formu.
     * 
     */
    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        ((JDialog)this.getTopLevelAncestor()).dispose();
    }//GEN-LAST:event_btnNazadActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNazad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAutomobil;
    private javax.swing.JLabel lblCena;
    private javax.swing.JLabel lblDatumKreiranja;
    private javax.swing.JLabel lblDatumZavrsetka;
    private javax.swing.JLabel lblKvar;
    private javax.swing.JLabel lblServiser;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblPokvareniDelovi;
    // End of variables declaration//GEN-END:variables

    /**
     * Priprema prikaz forme. 
     * 
     * Postavlja vrednosti svih labela i poziva metodu koja ta taj nalog vraca sve pokvarene delove iz baze.
     */
    private void prepareView() {
        tblPokvareniDelovi.setModel(new TableModelPokvarenDeo());
        lblAutomobil.setText(this.nalog.getKvar().getAutomobil().getTablice());
        lblKvar.setText(this.nalog.getKvar().getOpis());
        lblServiser.setText(this.nalog.getServiser().toString());
        lblDatumKreiranja.setText(this.nalog.getDatumKreiranja().toString());
        if(this.nalog.getStatus()==0){
            lblStatus.setText("U obradi...");
            lblStatus.setForeground(Color.DARK_GRAY);
        }else {
            lblStatus.setText("Zavrsen");
            lblStatus.setForeground(Color.GREEN);
        }
        if(this.nalog.getDatumIzvrsenja()==null){
            lblDatumZavrsetka.setText("/");
        }else{
            lblDatumZavrsetka.setText(this.nalog.getDatumIzvrsenja().toString());
        }
        lblCena.setText(this.nalog.getCena()+" €");
        
        vratiPokvareneDelove();
    }

    /**
     * Vraca listu svih pokvarenih delova za nalog iz baze i prikazuje ih u tabeli.
     * 
     * Poziva se metoda kontrolera koja pronalazi pokvarene delove prema odredjenom kriterijumu.
     * Ukoliko dodje do greske, ona se prikazuje serviseru.
     */
    private void vratiPokvareneDelove() {
        PokvareniDeo pd = new PokvareniDeo();
        pd.setUoceniKvar(this.nalog.getKvar());
        try {
            List<PokvareniDeo> pokvareniDelovi = Controller.getInstance().pronadjiPokvareneDelove(pd);
            ((TableModelPokvarenDeo)tblPokvareniDelovi.getModel()).setListaPokvarenihDelova(pokvareniDelovi);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju pokvarenih delova!\n"+ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }
}
